### ISSUE TITLE
Lack of clarity over control values

### ISSUE THREAD

**Issue by stevenfayers** [bipinshan/CustomNTONPCFMultiselectLookup#3]
Hi

There's a lack of clarity over 2 parts of the values to enter in the control.
1) For the entity names, lookup attributes, name attributes, does it expect the name or Schema name (which may contain capital letters)
2) It is unclear what the difference is between Relationship Name and Relationship Entity. What needs to be filled in here because the screenshot has the names truncated.

**Comment by bipinshan** [comment]
Hi,

1. It expects Name and not schema name.
2. You can pass any dummy value in both parameters, These are not being used in the code and will be removed in future releases.
