### ISSUE TITLE
Error during control load

### ISSUE THREAD

**Issue by staniko** [bipinshan/CustomNTONPCFMultiselectLookup#4]
https://github.com/bipinshan/CustomNTONPCFMultiselectLookup/blob/5bf727d0ee87f99c7bd96e59268cf6421425b3be/NToNMultiSelect/index.ts#L177

This cant work, missing blank before the "and":
` eq " + (<any>this.contextObj).page.entityId +"and `

**Comment by bipinshan** [comment]
This is fixed now


Thanks for your feedback.

**Comment by stevenfayers** [comment]
@bipinshan - is there a new solution version available with this fix?
